<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="CN-D-027" name="com.app.akku.work.TestCases.AKKU_48_Uploadcsvfile" tests="3" failures="1" timestamp="20 Nov 2017 13:51:09 GMT" time="98.995" errors="0">
  <testcase name="AK_39_AddBulkUserfromUploadfilewithValidData" time="35.769" classname="com.app.akku.work.TestCases.AKKU_48_Uploadcsvfile"/>
  <testcase name="AK_34_AddBulkUserfromUploadfileCSVwithInvalidData" time="32.647" classname="com.app.akku.work.TestCases.AKKU_48_Uploadcsvfile">
    <failure type="java.lang.AssertionError" message="expected [Upload failed invalid email id.] but found [Upload failed invalid CSV data..]">
      <![CDATA[java.lang.AssertionError: expected [Upload failed invalid email id.] but found [Upload failed invalid CSV data..]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.app.akku.work.pageobjects.usermanagement.Usermanagementpage.ValidateErrormsg(Usermanagementpage.java:156)
	at com.app.akku.work.TestCases.AKKU_48_Uploadcsvfile.AK_34_AddBulkUserfromUploadfileCSVwithInvalidData(AKKU_48_Uploadcsvfile.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- AK_34_AddBulkUserfromUploadfileCSVwithInvalidData -->
  <testcase name="AK_34_AddBulkUserfromUploadfileCSVwithInvalidData" time="30.579" classname="com.app.akku.work.TestCases.AKKU_48_Uploadcsvfile">
    <skipped/>
  </testcase> <!-- AK_34_AddBulkUserfromUploadfileCSVwithInvalidData -->
</testsuite> <!-- com.app.akku.work.TestCases.AKKU_48_Uploadcsvfile -->
